### ISSUE TITLE
Mixin conflict causes game crash with MoreChatHistory

### ISSUE THREAD

**Issue by 0xallie** [AzureAaron/aaron-mod#1]
I wanted this mod just for the feature to not reset cursor position when moving between chest pages, but it crashes when used together with MoreChatHistory:

https://mclo.gs/QumqkM7

**Comment by AzureAaron** [comment]
This has been fixed in the latest commit, I'm not sure when the next release will be so I recommend you compile the mod yourself. (as a bonus you'll get all the new features early!)

Thanks for using the mod :)
