### ISSUE TITLE
Crashes my game when I join a world

### ISSUE THREAD

**Issue by pigerstreet** [AzureAaron/aaron-mod#2]
Everytime I join a world with this mod on. my game crashes

**Comment by pigerstreet** [comment]
Now only crashes when I join Hypixel. Any other server is fine

**Comment by AzureAaron** [comment]
Do you have a log and crash report so I can look into it?

**Comment by pigerstreet** [comment]
This only happens on the version for 1.20.2. After I reverted to 1.20.1 I never had anymore crashes. Ill see if I can find a log

**Comment by pigerstreet** [comment]
Also I've got a suggestion to add some features that would help with kuudra such as beacons/waypoints for supplies and such

**Comment by AzureAaron** [comment]
Are you sure you're using a version of the mod made for 1.20.2? I can only debug it if I have a log/crash report to go off of.

For the Kuudra features I would recommend requesting that to Skyblocker because its a bit out of scope here.

**Comment by AzureAaron** [comment]
As this has been open for a while and is based on an older version of the mod I'm going to close it. If this happens again feel free to open another issue with the appropriate information.
