### ISSUE TITLE
pls fix this

### ISSUE THREAD

**Issue by nickademas** [AzureAaron/aaron-mod#3]
https://github.com/RaphiMC/ImmediatelyFast/issues/194

**Comment by AzureAaron** [comment]
In the next version (1.3.0) the aforementioned core shader will become part of a builtin resource pack that is enabled by default so that if anything breaks you can turn it off :)

**Comment by AzureAaron** [comment]
Hi sorry I wasn't able to reply for a few weeks but the `1.3.0` version for Minecraft 1.21 moved the core shader to an optional resource pack provided by the mod that you can disable. To fix this you can of course just turn it off now :)

Thanks for reporting this and for using my mod, enjoy!
