### ISSUE TITLE
/textreplacer displays entries in a nondeterministic order

### ISSUE THREAD

**Issue by MacchuPicchu3** [AzureAaron/aaron-mod#5]
The command `/textreplacer` does not seem to sort the order in which entries are displayed. Instead, it's completely random. For most entries, this will not be an issue, but in cases where one entry string is a subset of another entry string, it becomes impossible to control the mod's behavior.

I'll illustrate with my desired use case. I would like for my item tooltips to display t6 enchantments in one color and t7 enchantments in a different color. Importantly, I prefer my enchantments to use Roman numerals. (Attached is a screenshot of what my tooltips would ideally look like.)

Now, take the Sharpness enchantment as an example. If I try to set `Sharpness VI` to dark blue and `Sharpness VII` to red, then Aaron's mod will work for the t6 but not the t7. It will color `Sharpness VII` in dark blue, except for the last `I`, which will correctly show in red. 

When brought up on the Skyblocker discord, you said you might make use of a LinkedHashMap to address this, as opposed to something like Regex, which could also work.

![Skyblock_HyperionEnchants](https://github.com/user-attachments/assets/00641ff7-ba22-4dd0-b9cb-b3c6eb62bc8d)

**Comment by AzureAaron** [comment]
I swapped it to a LinkedHashMap in the new 1.4.0 release so it should respect insertion order, if this isn't sufficient let me know.

**Comment by MacchuPicchu3** [comment]
It works correctly according to my initial testing. I would recommend that you mention this feature in the config sidebar so that people know. Thank you so much!
