### ISSUE TITLE
Chroma Colors do not go chroma upon leaving and relogging into the game (1.21.1)

### ISSUE THREAD

**Issue by zjjohn121110** [AzureAaron/aaron-mod#8]
When initially downloading the mod, chroma colors do work, but once the game is closed and you log out, once you log back in chroma colors are brown, but if you redownload the mod, it fixes the issue until you log out again.
![2024-11-29_22 22 00](https://github.com/user-attachments/assets/a7c85ffb-10f6-4c35-b31e-b0a3fc7e8086)
(screenshot is of a maxed claymore on ah)

**Comment by AzureAaron** [comment]
This happens because the resource that provides the chroma text shader is not enabled, you will need to have it enabled in order for the effect to work.
